name: Deploy Backend

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'production'
    
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Enable error logging
          set -e
          exec 2> >(tee /tmp/deploy_error.log >&2)
          
          echo "=== Starting deployment at $(date) ==="
          
          # Install dependencies (Docker, Git)
          echo "Installing required packages..."
          sudo yum update -y
          sudo yum install -y git docker yum-utils
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker ec2-user
          echo "Dependency installation completed"

          # Remove old code completely
          echo "Cleaning up previous deployment..."
          cd /home/ec2-user
          sudo rm -rf dojeon-backend
          mkdir -p dojeon-backend
          cd dojeon-backend
          echo "Cleaned and entered: $(pwd)"
          
          # Clone latest code
          echo "Cloning latest code..."
          git clone https://github.com/kwohyuno/dojeon-BE.git .
          echo "Git clone completed"
          
          # Check Java installation
          echo "Checking Java installation..."
          if ! command -v java &> /dev/null; then
            echo "Installing Java 17..."
            sudo yum install -y java-17-amazon-corretto
            echo "Java installation completed"
          else
            echo "Java already installed: $(java -version)"
          fi
          
          # Check Maven installation
          echo "Checking Maven installation..."
          if ! command -v mvn &> /dev/null; then
            echo "Installing Maven..."
            sudo yum install -y maven
            echo "Maven installation completed"
          else
            echo "Maven already installed: $(mvn -version)"
          fi
          
          # Build with Maven
          echo "Building with Maven..."
          ./mvnw clean package -DskipTests
          echo "Maven build completed"
          
          # Stop existing container
          echo "Stopping existing container..."
          sudo docker stop dojeon-backend || echo "No existing container to stop"
          sudo docker rm dojeon-backend || echo "No existing container to remove"
          
          # Build Docker image
          echo "Building Docker image..."
          sudo docker build -t dojeon-backend:latest .
          echo "Docker build completed"
          
          # Run new container
          echo "Starting new container..."
          sudo docker run -d \
            --name dojeon-backend \
            --restart unless-stopped \
            -p 8080:8080 \
            -e SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
            -e SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
            -e SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
            -e SPRING_JPA_HIBERNATE_DDL_AUTO=${{ secrets.SPRING_JPA_HIBERNATE_DDL_AUTO }} \
            dojeon-backend:latest
          
          # Verify container is running
          echo "Verifying container status..."
          sleep 10
          sudo docker ps | grep dojeon-backend || echo "Container not found in docker ps"
          
          # Check container logs
          echo "Container logs:"
          sudo docker logs dojeon-backend --tail 20 || echo "Failed to get container logs"
          
          # Clean up old images
          echo "Cleaning up old images..."
          sudo docker image prune -f
          
          echo "=== Deployment completed at $(date) ==="
          
          # Show error log if exists
          if [ -f /tmp/deploy_error.log ]; then
            echo "=== Error Log ==="
            cat /tmp/deploy_error.log
          fi
